/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PriceRange = { 'expensive' : null } |
  { 'budget' : null } |
  { 'moderate' : null };
export interface Restaurant {
  'hours' : string,
  'name' : string,
  'cuisineType' : string,
  'priceRange' : PriceRange,
  'address' : string,
  'rating' : bigint,
  'menuHighlights' : Array<string>,
}
export interface _SERVICE {
  'addRestaurant' : ActorMethod<
    [string, string, PriceRange, bigint, string, string, Array<string>],
    undefined
  >,
  'filterByCuisineType' : ActorMethod<[string], Array<Restaurant>>,
  'filterByMinimumRating' : ActorMethod<[bigint], Array<Restaurant>>,
  'filterByPriceRange' : ActorMethod<[PriceRange], Array<Restaurant>>,
  'getAllRestaurants' : ActorMethod<[], Array<Restaurant>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];