/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PriceRange = IDL.Variant({
  'expensive' : IDL.Null,
  'budget' : IDL.Null,
  'moderate' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'cuisineType' : IDL.Text,
  'priceRange' : PriceRange,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'menuHighlights' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addRestaurant' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        PriceRange,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'filterByCuisineType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'filterByMinimumRating' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'filterByPriceRange' : IDL.Func(
      [PriceRange],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PriceRange = IDL.Variant({
    'expensive' : IDL.Null,
    'budget' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'cuisineType' : IDL.Text,
    'priceRange' : PriceRange,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'menuHighlights' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addRestaurant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          PriceRange,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'filterByCuisineType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'filterByMinimumRating' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'filterByPriceRange' : IDL.Func(
        [PriceRange],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'getAllRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };